[package]
name = "update_jwk"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-core.git"
rev = "devnet"
subdir = "cedra-move/framework/cedra-framework"

[dev-dependencies]
