blank_issues_enabled: true
contact_links:
  - name: Questions and Help (on Cedra Developer Discussions)
    url: (https://github.com/cedra-labs/cedra-developer-discussions/discussions
    about: Support and other Questions are handled by the team and the community on Cedra Developer Discussions.
  - name: Questions, Help and Chat (on Discord)
    url: https://discord.gg/cedranetwork
    about: Contact the development team, contributors and community on Discord
