[package]
name = "transferAndPay"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-network.git"
rev = "mainnet"
subdir = "cedra-move/framework/cedra-framework"
