[package]
name = "Claims"
version = "1.0.0"
authors = []

[addresses]
my_addr = "_"

[dev-addresses]
my_addr = "0x12345"

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-core.git"
rev = "mainnet"
subdir = "cedra-move/framework/cedra-framework"
