[package]
name = "MoonCoin"
version = "0.0.0"

[addresses]
MoonCoin = "_"

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-network.git"
rev = "mainnet"
subdir = "cedra-move/framework/cedra-framework"
