[package]
name = "facoin"
version = "1.0.0"
authors = []

[addresses]
FACoin = "_"

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-network.git"
rev = "mainnet"
subdir = "cedra-move/framework/cedra-framework"
